name: Java CI with Maven and JaCoCo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven with Debug Info
        run: mvn clean verify -X -Pexclude-e2e-tests  # Ejecutar con el perfil para excluir pruebas E2E

      # Subir solo el reporte HTML de JaCoCo, si existe
      - name: Compress JaCoCo HTML report if it exists
        run: |
          if [ -d "target/jacoco-reports" ]; then
            zip -r jacoco-report.zip target/jacoco-reports/index.html
          else
            echo "JaCoCo report directory not found, skipping compression."
          fi

      - name: Upload compressed JaCoCo report if it exists
        if: success() && steps.compress.outputs.exists == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-html-report
          path: jacoco-report.zip

      - name: Check test results
        run: |
          if grep -q "FAIL" target/surefire-reports/*.txt; then
            echo "Tests failed!"
            exit 1
          else
            echo "Tests passed!"
          fi

      - name: Wait for the test environment (Optional)
        run: |
          echo "Waiting for environment to settle..."
          sleep 10
